#### NUMPY BASICS PRACTICE


### 1. Create arrays

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array 1:", arr1)
print("Array 2:\n", arr2)

Array 1: [1 2 3 4 5]
Array 2:
 [[1 2 3]
 [4 5 6]]


### 2. Array shape & dtype


In [2]:
print("\nShape of arr1:", arr1.shape)
print("Data type of arr1:", arr1.dtype)

print("Shape of arr2:", arr2.shape)
print("Data type of arr2:", arr2.dtype)


Shape of arr1: (5,)
Data type of arr1: int64
Shape of arr2: (2, 3)
Data type of arr2: int64


###  3. Zeros and Ones

In [3]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))

print("\nZeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4. Arange and linspace

In [4]:
arange_array = np.arange(1, 10, 2)
linspace_array = np.linspace(0, 1, 5)

print("\nArange Array:", arange_array)
print("Linspace Array:", linspace_array)


Arange Array: [1 3 5 7 9]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### 5. Indexing & slicing

In [5]:
arr = np.array([10, 20, 30, 40, 50])

print("\nFirst element:", arr[0])
print("Last element:", arr[-1])
print("Slice (index 1 to 3):", arr[1:4])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 1, col 2:", matrix[1, 2])




First element: 10
Last element: 50
Slice (index 1 to 3): [20 30 40]
Element at row 1, col 2: 6


### 6. Basic operations

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)



Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


### 7. Mean, Sum, Max, Min

In [7]:
nums = np.array([10, 20, 30, 40, 50,60,70,80,90,100])

print("\nMean:", np.mean(nums))
print("Sum:", np.sum(nums))
print("Max:", np.max(nums))
print("Min:", np.min(nums))


Mean: 55.0
Sum: 550
Max: 100
Min: 10
